import { useEffect, useRef, useState } from "react";
import "./styles.css";

type Point = { x: number; y: number };
type Stroke = { points: Point[]; color: string; width: number; opacity: number; tool: string };
const palette = ["#17191f", "#ef4444", "#f59e0b", "#22c55e", "#06b6d4", "#3b82f6", "#8b5cf6", "#ec4899", "#ffffff"];
const tools = ["brush", "pencil", "marker", "highlighter", "eraser", "line", "arrow", "rectangle", "ellipse", "text", "mask"];
const read = <T,>(k: string, d: T): T => { try { return JSON.parse(localStorage.getItem(k) || "null") ?? d; } catch { return d; } };
export default function App() {
 const ref=useRef<HTMLCanvasElement>(null), [tool,setTool]=useState("brush"),[color,setColor]=useState("#17191f"),[size,setSize]=useState(8),[prompt,setPrompt]=useState(read("prompt","")),[strength,setStrength]=useState(72),[strokes,setStrokes]=useState<Stroke[]>(()=>read("strokes",[])),[past,setPast]=useState<Stroke[][]>([]),[future,setFuture]=useState<Stroke[][]>([]),[tab,setTab]=useState("canvas"),[generating,setGenerating]=useState(false),[history,setHistory]=useState<string[]>(()=>read("history",[]));
 useEffect(()=>{localStorage.setItem("strokes",JSON.stringify(strokes)); localStorage.setItem("prompt",JSON.stringify(prompt));localStorage.setItem("history",JSON.stringify(history));draw(strokes)},[strokes,prompt,history]);
 useEffect(()=>{const f=()=>draw(strokes);window.addEventListener("resize",f);return()=>window.removeEventListener("resize",f)},[strokes]);
 function draw(ss:Stroke[]){const c=ref.current;if(!c)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext("2d")!;x.setTransform(d,0,0,d,0,0);x.fillStyle="#faf9f6";x.fillRect(0,0,r.width,r.height);for(const s of ss){if(!s.points.length)continue;x.save();x.globalAlpha=s.opacity;x.globalCompositeOperation=s.tool==="eraser"?"destination-out":"source-over";x.strokeStyle=s.color;x.lineWidth=s.width;x.lineCap="round";x.lineJoin="round";x.beginPath();x.moveTo(s.points[0].x,s.points[0].y);s.points.slice(1).forEach(p=>x.lineTo(p.x,p.y));x.stroke();x.restore()}}
 function pos(e:React.PointerEvent<HTMLCanvasElement>){const r=ref.current!.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
 function down(e:React.PointerEvent<HTMLCanvasElement>){if(tool==="text"){const p=pos(e);const t=window.prompt("Canvas text","AI guidance");if(t)setStrokes(s=>[...s,{points:[p],color,width:size,opacity:1,tool:"text"}]);return}setPast(p=>[...p,strokes]);setFuture([]);e.currentTarget.setPointerCapture(e.pointerId);(e.currentTarget as any)._stroke={points:[pos(e)],color,width:tool==="highlighter"?size*4:size,opacity:tool==="highlighter"?.2:tool==="marker"?.65:1,tool};}
 function move(e:React.PointerEvent<HTMLCanvasElement>){const s=(e.currentTarget as any)._stroke as Stroke;if(!s)return;s.points.push(pos(e));setStrokes(v=>[...v.slice(0,-1),s]);}
 function end(e:React.PointerEvent<HTMLCanvasElement>){delete (e.currentTarget as any)._stroke}
 function undo(){const p=past.at(-1);if(!p)return;setFuture(f=>[...f,strokes]);setStrokes(p);setPast(past.slice(0,-1))} function redo(){const n=future.at(-1);if(!n)return;setPast(p=>[...p,strokes]);setStrokes(n);setFuture(future.slice(0,-1))}
 function gen(){setGenerating(true);setTimeout(()=>{setHistory(h=>[`generation-${Date.now()}`,...h].slice(0,50));setGenerating(false)},700)}
 return <div className="app"><header><strong>✦ Real-Time AI Canvas</strong><nav>{[["canvas","Canvas"],["i2i","Image → Image"],["history","History"]].map(([id,n])=><button className={tab===id?"tab active":"tab"} onClick={()=>setTab(id)} key={id}>{n}</button>)}</nav></header>{tab==="canvas"&&<main className="workspace"><aside className="tools">{tools.map(t=><button className={tool===t?"tool active":"tool"} onClick={()=>setTool(t)} key={t}>{t==="eraser"?"⌫":t==="arrow"?"➜":t==="rectangle"?"□":t==="ellipse"?"○":t==="text"?"T":"•"}</button>)}<hr/><button className="tool" onClick={undo}>↶</button><button className="tool" onClick={redo}>↷</button><button className="tool" onClick={()=>setStrokes([])}>⌧</button></aside><section className="pane"><div className="head">DRAWING CANVAS <span>{tool}</span></div><div className="stage"><canvas ref={ref} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/></div></section><section className="pane"><div className="head">LIVE AI PREVIEW <span className={generating?"live generating":"live"}>● {generating?"Generating":"Listening"}</span></div><div className="preview"><div className="art"/><div className={generating?"scan on":"scan"}/></div><small>Canvas + prompt + annotations form generation context.</small></section><aside className="controls"><label>AI GUIDANCE</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe what you want the AI to create…"/><label>MODEL</label><select><option>Best Free / Open Model</option><option>Fast Draft</option><option>High Quality</option></select><label>GENERATION STRENGTH <b>{strength}%</b></label><input type="range" min="0" max="100" value={strength} onChange={e=>setStrength(+e.target.value)}/><label>BRUSH SIZE <b>{size}px</b></label><input type="range" min="1" max="80" value={size} onChange={e=>setSize(+e.target.value)}/><label>COLOR</label><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><div className="palette">{palette.map(c=><button key={c} style={{background:c}} onClick={()=>setColor(c)}/>)}</div><button className="generate" onClick={gen}>{generating?"GENERATING…":"GENERATE NOW"}</button></aside></main>}{tab==="i2i"&&<main className="mode"><h2>Image → Image</h2><div className="i2i"><div className="drop">Drop a source image here</div><div className="preview"><div className="art"/></div></div><div className="bar"><input placeholder="Describe the transformation…"/><button className="generate" onClick={gen}>GENERATE</button></div></main>}{tab==="history"&&<main className="mode"><h2>Generation History</h2><div className="gallery">{history.map((h,i)=><div className="thumb" key={h}><div className="art"/><span>Generation {history.length-i}</span></div>)}{!history.length&&<p>No generations yet.</p>}</div></main>}<footer>Local persistence · {strokes.length} strokes · {history.length} generations</footer></div>;
}
